var classes = [
    {
        "name": "Tina4\\Debug",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "message",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getColor",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "emergency",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "alert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "critical",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "error",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "warning",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "notice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "info",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "debug",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 25,
        "ccn": 15,
        "ccnMethodMax": 8,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 135,
        "vocabulary": 34,
        "volume": 686.81,
        "difficulty": 20.83,
        "effort": 14308.49,
        "level": 0.05,
        "bugs": 0.23,
        "time": 795,
        "intelligentContent": 32.97,
        "number_operators": 35,
        "number_operands": 100,
        "number_operators_unique": 10,
        "number_operands_unique": 24,
        "cloc": 61,
        "loc": 155,
        "lloc": 94,
        "mi": 76.37,
        "mIwoC": 35.08,
        "commentWeight": 41.3,
        "kanDefect": 0.72,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 44,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 55,
        "package": "Tina4\r\\",
        "pageRank": 0.33,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Tina4\\DebugCodeHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCodeSnippet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 78,
        "vocabulary": 26,
        "volume": 366.63,
        "difficulty": 15.31,
        "effort": 5614.09,
        "level": 0.07,
        "bugs": 0.12,
        "time": 312,
        "intelligentContent": 23.94,
        "number_operators": 29,
        "number_operands": 49,
        "number_operators_unique": 10,
        "number_operands_unique": 16,
        "cloc": 10,
        "loc": 39,
        "lloc": 29,
        "mi": 84.66,
        "mIwoC": 49.34,
        "commentWeight": 35.32,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "Tina4\r\\",
        "pageRank": 0.33,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Tina4\\DebugErrorHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "errorHandler",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Tina4\\Debug",
            "Tina4\\DebugCodeHandler"
        ],
        "parents": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 19,
        "volume": 152.93,
        "difficulty": 1.71,
        "effort": 260.87,
        "level": 0.59,
        "bugs": 0.05,
        "time": 14,
        "intelligentContent": 89.65,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 2,
        "number_operands_unique": 17,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 109.37,
        "mIwoC": 63.75,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "Tina4\r\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Tina4\\DebugExceptionHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "exceptionHandler",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Tina4\\Debug",
            "Tina4\\Debug",
            "Tina4\\DebugCodeHandler",
            "Tina4\\DebugCodeHandler",
            "Tina4\\DebugRender"
        ],
        "parents": [],
        "lcom": 1,
        "length": 73,
        "vocabulary": 19,
        "volume": 310.1,
        "difficulty": 7.07,
        "effort": 2191.36,
        "level": 0.14,
        "bugs": 0.1,
        "time": 122,
        "intelligentContent": 43.88,
        "number_operators": 20,
        "number_operands": 53,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 11,
        "loc": 33,
        "lloc": 22,
        "mi": 91.59,
        "mIwoC": 52.6,
        "commentWeight": 38.99,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "Tina4\r\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Tina4\\DebugRender",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "renderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Twig\\Loader\\FilesystemLoader",
            "Twig\\Environment"
        ],
        "parents": [],
        "lcom": 2,
        "length": 38,
        "vocabulary": 19,
        "volume": 161.42,
        "difficulty": 4.38,
        "effort": 707.77,
        "level": 0.23,
        "bugs": 0.05,
        "time": 39,
        "intelligentContent": 36.82,
        "number_operators": 19,
        "number_operands": 19,
        "number_operators_unique": 6,
        "number_operands_unique": 13,
        "cloc": 19,
        "loc": 46,
        "lloc": 27,
        "mi": 94.6,
        "mIwoC": 52.64,
        "commentWeight": 41.96,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 12,
        "package": "Tina4\r\\",
        "pageRank": 0.15,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    }
]